#pragma once
// GENERATED by firmware/scripts/gen_tz_table.py from nayarsystems/posix_tz_db@93447c0ddac3 (MIT, see firmware/THIRD_PARTY_NOTICES.md).
// Do not edit by hand. Lookup helpers: miblo_tz.h.
#include <stddef.h>

namespace miblo {

constexpr size_t kTzCount = 461;
constexpr size_t kTzNamesLen = 7390;  // bytes, without the terminating NUL
constexpr size_t kTzNameMax = 30;  // the longest name, bytes
// Sorted IANA names, each followed by '\n' (MIBLO_ROM: read with mibloRomByte).
extern const char kTzNames[];
// POSIX TZ rules in the same order, each followed by '\n' (MIBLO_ROM).
extern const char kTzPosix[];

}  // namespace miblo
