#!/usr/bin/env python3
"""Generates the IANA -> POSIX time zone table embedded in the firmware (flash, MIBLO_ROM).

Source: nayarsystems/posix_tz_db (MIT), `zones.csv` at a pinned commit. Each row is
"<IANA name>","<POSIX TZ rule>". The output is two blobs in the same (sorted) order:
  kTzNames: "Africa/Abidjan\\nAfrica/Accra\\n..."  (served as-is by GET /api/zones)
  kTzRules: "<+0330>-3:30\\nAEST-10\\n..."  (each distinct POSIX rule once, sorted)
  kTzRule:  {41, 41, ...}  (per name, the index of its rule in kTzRules)
Many zones share a rule (all of "GMT0", "CET-1CEST,M3.5.0,M10.5.0/3", ...): ~93 distinct rules
for ~460 names, so each rule is stored once and indexed (~4 KB less flash than one per name).
Run it again (with a new COMMIT) to pick up tz database updates; the result is committed.

Usage: python3 firmware/scripts/gen_tz_table.py [path/to/zones.csv]
"""
import csv
import io
import os
import sys
import urllib.request

COMMIT = "93447c0ddac304ca6672a5fd905261c7e8905159"
URL = f"https://raw.githubusercontent.com/nayarsystems/posix_tz_db/{COMMIT}/zones.csv"
HERE = os.path.dirname(os.path.abspath(__file__))
DEST = os.path.join(HERE, "..", "lib", "miblo_core", "src")
MAX_NAME = 47  # Config::tz is char[48]
MAX_POSIX = 47  # the resolved rule buffer is 48 bytes


def load(argv):
    if len(argv) > 1:
        with open(argv[1], encoding="utf-8") as f:
            return f.read()
    with urllib.request.urlopen(URL, timeout=30) as r:
        return r.read().decode("utf-8")


def c_string(s, indent="    "):
    """Splits `s` into lines of C string literals (one zone per line)."""
    out = []
    for line in s.splitlines(keepends=True):
        esc = line.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        out.append(f'{indent}"{esc}"')
    return "\n".join(out)


def c_bytes(values, indent="    ", per_line=24):
    """Comma-separated numbers, `per_line` per line."""
    lines = []
    for i in range(0, len(values), per_line):
        lines.append(indent + ", ".join(str(v) for v in values[i:i + per_line]) + ",")
    return "\n".join(lines)


def main(argv):
    rows = []
    for row in csv.reader(io.StringIO(load(argv))):
        if not row:
            continue
        name, rule = row[0].strip(), row[1].strip()
        for s in (name, rule):
            if not s or any(ord(c) < 0x21 or ord(c) > 0x7E for c in s):
                sys.exit(f"unexpected characters in row {row!r}")
        if len(name) > MAX_NAME or len(rule) > MAX_POSIX:
            sys.exit(f"row too long: {row!r}")
        rows.append((name, rule))
    rows.sort()
    names = "".join(n + "\n" for n, _ in rows)
    distinct = sorted({r for _, r in rows})
    if len(distinct) > 256:
        sys.exit("more than 256 distinct rules: kTzRule needs wider entries")
    rules = "".join(r + "\n" for r in distinct)
    index = [distinct.index(r) for _, r in rows]
    src = f"nayarsystems/posix_tz_db@{COMMIT[:12]} (MIT, see firmware/THIRD_PARTY_NOTICES.md)"

    header = f"""#pragma once
// GENERATED by firmware/scripts/gen_tz_table.py from {src}.
// Do not edit by hand. Lookup helpers: miblo_tz.h.
#include <stddef.h>

namespace miblo {{

constexpr size_t kTzCount = {len(rows)};
constexpr size_t kTzNamesLen = {len(names)};  // bytes, without the terminating NUL
constexpr size_t kTzNameMax = {max(len(n) for n, _ in rows)};  // the longest name, bytes
// Sorted IANA names, each followed by '\\n' (MIBLO_ROM: read with mibloRomByte).
extern const char kTzNames[];
constexpr size_t kTzRuleCount = {len(distinct)};
// The distinct POSIX TZ rules, each followed by '\\n' (MIBLO_ROM).
extern const char kTzRules[];
// For each name (same order as kTzNames), the index of its rule in kTzRules (MIBLO_ROM).
extern const unsigned char kTzRule[];

}}  // namespace miblo
"""
    body = f"""// GENERATED by firmware/scripts/gen_tz_table.py from {src}.
// Do not edit by hand.
#include "miblo_tz_table.h"

#include "miblo_rom.h"

namespace miblo {{

// {len(names)} bytes
const char kTzNames[] MIBLO_ROM =
{c_string(names)};

// {len(rules)} bytes
const char kTzRules[] MIBLO_ROM =
{c_string(rules)};

const unsigned char kTzRule[] MIBLO_ROM = {{
{c_bytes(index)}
}};

}}  // namespace miblo
"""
    with open(os.path.join(DEST, "miblo_tz_table.h"), "w", encoding="utf-8", newline="\n") as f:
        f.write(header)
    with open(os.path.join(DEST, "miblo_tz_table.cpp"), "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    print(f"{len(rows)} zones, names {len(names)} B, {len(distinct)} rules {len(rules)} B")


if __name__ == "__main__":
    main(sys.argv)
