#!/usr/bin/env python3
"""Vendors U8g2_for_TFT_eSPI (Bodmer) + only the u8g2 fonts Miblo uses, in PROGMEM.

Why vendor it: on the ESP8266 the original library leaves the fonts in `.rodata` (RAM!) and
reads the bytes with a direct pointer. The patch below puts the fonts in `.irom.text` (flash)
and swaps the read for pgm_read_byte — same as what official u8g2 does for the ESP8266. Run
once; the result (lib/U8g2TFT/) is committed.

Usage: firmware/.venv/bin/python firmware/scripts/vendor_u8g2.py
"""
import codecs
import os
import re
import sys
import urllib.request

COMMIT = "a170ef8b6d8414b1ee2ecc97b5b913e08f5597ac"
BASE = f"https://raw.githubusercontent.com/Bodmer/U8g2_for_TFT_eSPI/{COMMIT}"
HERE = os.path.dirname(os.path.abspath(__file__))
DEST = os.path.join(HERE, "..", "lib", "U8g2TFT", "src")

# Fonts used by src/display.cpp (text styles). Total size ~= 224 KB.
FONTS = [
    "u8g2_font_helvR10_te",
    "u8g2_font_helvB10_te",
    "u8g2_font_helvR12_te",
    "u8g2_font_helvB12_te",
    "u8g2_font_helvB18_te",
    "u8g2_font_helvB24_te",
    "u8g2_font_fub20_tf",
    "u8g2_font_fub30_tn",
    "u8g2_font_6x13_t_cyrillic",
    "u8g2_font_6x13B_t_cyrillic",
    "u8g2_font_8x13_t_cyrillic",
    "u8g2_font_10x20_t_cyrillic",
    "u8g2_font_inr24_t_cyrillic",
    "u8g2_font_wqy14_t_gb2312a",
]

# Fonts only used for a few characters: vendored as a subset (same glyph data and metrics, the
# other glyphs dropped) under a new name. fub20 draws percentages and "--" (NumM) and the "%"
# fallback of the big numbers (NumL), so the full 5.4 KB font is not needed.
SUBSETS = {
    "u8g2_font_fub20_tf": ("u8g2_font_fub20_miblo", " %+,-./0123456789:"),
}

PATCH = """
/* --- Miblo: fonts in flash on the ESP8266 (same as official u8g2) --- */
#if defined(ESP8266)
#  include <pgmspace.h>
#  define U8X8_FONT_SECTION(name) __attribute__((section(".irom.text." name)))
#  define u8x8_pgm_read(adr) pgm_read_byte(adr)
#  define U8X8_PROGMEM
#endif
/* --- end of Miblo patch --- */

"""


def fetch(path):
    with urllib.request.urlopen(f"{BASE}/{path}", timeout=120) as r:
        # latin-1 preserves the bytes exactly (some comments are not valid UTF-8)
        return r.read().decode("latin-1")


def font_bytes(lines):
    """The bytes of a u8g2 font from its C definition lines."""
    body = "\n".join(lines)
    body = body[body.index("=") + 1:]
    lits = re.findall(r'"((?:[^"\\]|\\.)*)"', body, re.S)
    return b"".join(codecs.escape_decode(l.encode("latin-1"))[0] for l in lits)


def subset_font(data, chars):
    """u8g2 font with only the 8-bit glyphs in `chars` (no Unicode section).

    Layout: 23-byte header (glyph count at 0; offsets of 'A', 'a' and the Unicode table at
    17..22, big endian, relative to byte 23), then glyph records [encoding, size, bits...]
    ended by [0, 0], then the Unicode table ([0, 4, 0xFF, 0xFF] = empty).
    """
    keep = {ord(c) for c in chars}
    glyphs, p = [], 23
    while data[p + 1]:
        if data[p] in keep:
            glyphs.append(data[p:p + data[p + 1]])
        p += data[p + 1]
    body = b"".join(glyphs) + b"\0\0"
    uni = len(body)
    header = bytearray(data[:23])
    header[0] = len(glyphs)
    header[17:21] = b"\0\0\0\0"  # no 'A'/'a' shortcuts: lookups scan from the first glyph
    header[21], header[22] = uni >> 8, uni & 0xFF
    return bytes(header) + body + b"\0\4\377\377"


def font_c(name, data):
    """C definition of a font, in the u8g2 style (octal escapes, 64 bytes per line)."""
    out = [f'const uint8_t {name}[{len(data) + 1}] U8G2_FONT_SECTION("{name}") = ']
    for i in range(0, len(data), 64):
        # 3-digit octal escapes: a following digit can never be read as part of one
        chunk = "".join(chr(b) if 32 <= b < 127 and chr(b) not in '"\\?' else f"\\{b:03o}" for b in data[i:i + 64])
        out.append(f'  "{chunk}"')
    out[-1] += ";"
    return out


def main():
    os.makedirs(DEST, exist_ok=True)
    for name in ["U8g2_for_TFT_eSPI.h", "U8g2_for_TFT_eSPI.cpp"]:
        with open(os.path.join(DEST, name), "w", encoding="latin-1") as f:
            f.write(fetch(f"src/{name}"))
    with open(os.path.join(DEST, "LICENSE"), "w", encoding="latin-1") as f:
        f.write(fetch("LICENSE"))

    header = fetch("src/u8g2_fonts.h")
    anchor = "#ifndef U8X8_FONT_SECTION"
    if anchor not in header:
        sys.exit("u8g2_fonts.h changed: patch anchor not found")
    header = header.replace(anchor, PATCH + anchor, 1)
    with open(os.path.join(DEST, "u8g2_fonts.h"), "w", encoding="latin-1") as f:
        f.write(header)

    print("downloading u8g2_fonts.c (~26 MB)...")
    source = fetch("src/u8g2_fonts.c").split("\n")
    out = ['/* Generated by scripts/vendor_u8g2.py - only the fonts used by Miblo. */',
           '#include "u8g2_fonts.h"', ""]
    total = 0
    for font in FONTS:
        start = next((i for i, l in enumerate(source) if l.startswith(f"const uint8_t {font}[")), None)
        if start is None:
            sys.exit(f"font not found: {font}")
        end = start
        while not source[end].rstrip().endswith('";'):
            end += 1
        lines = source[start:end + 1]
        if font in SUBSETS:
            name, chars = SUBSETS[font]
            lines = font_c(name, subset_font(font_bytes(lines), chars))
            font = name
        out.extend(lines)
        out.append("")
        size = int(re.search(r"\[(\d+)\]", lines[0]).group(1))
        total += size
        print(f"  {font}: {size} bytes")
    with open(os.path.join(DEST, "miblo_fonts.c"), "w", encoding="latin-1") as f:
        f.write("\n".join(out) + "\n")
    print(f"total font size: {total} bytes")


if __name__ == "__main__":
    main()
