#!/usr/bin/env python3
"""Vendors U8g2_for_TFT_eSPI (Bodmer) + only the u8g2 fonts Miblo uses, in PROGMEM.

Why vendor it: on the ESP8266 the original library leaves the fonts in `.rodata` (RAM!) and
reads the bytes with a direct pointer. The patch below puts the fonts in `.irom.text` (flash)
and swaps the read for pgm_read_byte — same as what official u8g2 does for the ESP8266. Run
once; the result (lib/U8g2TFT/) is committed.

Usage: firmware/.venv/bin/python firmware/scripts/vendor_u8g2.py
"""
import os
import re
import sys
import urllib.request

COMMIT = "a170ef8b6d8414b1ee2ecc97b5b913e08f5597ac"
BASE = f"https://raw.githubusercontent.com/Bodmer/U8g2_for_TFT_eSPI/{COMMIT}"
HERE = os.path.dirname(os.path.abspath(__file__))
DEST = os.path.join(HERE, "..", "lib", "U8g2TFT", "src")

# Fonts used by src/display.cpp (text styles). Total size ~= 224 KB.
FONTS = [
    "u8g2_font_helvR10_te",
    "u8g2_font_helvB10_te",
    "u8g2_font_helvR12_te",
    "u8g2_font_helvB12_te",
    "u8g2_font_helvB18_te",
    "u8g2_font_helvB24_te",
    "u8g2_font_fub20_tf",
    "u8g2_font_fub30_tn",
    "u8g2_font_6x13_t_cyrillic",
    "u8g2_font_6x13B_t_cyrillic",
    "u8g2_font_8x13_t_cyrillic",
    "u8g2_font_10x20_t_cyrillic",
    "u8g2_font_inr24_t_cyrillic",
    "u8g2_font_wqy14_t_gb2312a",
]

PATCH = """
/* --- Miblo: fonts in flash on the ESP8266 (same as official u8g2) --- */
#if defined(ESP8266)
#  include <pgmspace.h>
#  define U8X8_FONT_SECTION(name) __attribute__((section(".irom.text." name)))
#  define u8x8_pgm_read(adr) pgm_read_byte(adr)
#  define U8X8_PROGMEM
#endif
/* --- end of Miblo patch --- */

"""


def fetch(path):
    with urllib.request.urlopen(f"{BASE}/{path}", timeout=120) as r:
        # latin-1 preserves the bytes exactly (some comments are not valid UTF-8)
        return r.read().decode("latin-1")


def main():
    os.makedirs(DEST, exist_ok=True)
    for name in ["U8g2_for_TFT_eSPI.h", "U8g2_for_TFT_eSPI.cpp"]:
        with open(os.path.join(DEST, name), "w", encoding="latin-1") as f:
            f.write(fetch(f"src/{name}"))
    with open(os.path.join(DEST, "LICENSE"), "w", encoding="latin-1") as f:
        f.write(fetch("LICENSE"))

    header = fetch("src/u8g2_fonts.h")
    anchor = "#ifndef U8X8_FONT_SECTION"
    if anchor not in header:
        sys.exit("u8g2_fonts.h changed: patch anchor not found")
    header = header.replace(anchor, PATCH + anchor, 1)
    with open(os.path.join(DEST, "u8g2_fonts.h"), "w", encoding="latin-1") as f:
        f.write(header)

    print("downloading u8g2_fonts.c (~26 MB)...")
    source = fetch("src/u8g2_fonts.c").split("\n")
    out = ['/* Generated by scripts/vendor_u8g2.py - only the fonts used by Miblo. */',
           '#include "u8g2_fonts.h"', ""]
    total = 0
    for font in FONTS:
        start = next((i for i, l in enumerate(source) if l.startswith(f"const uint8_t {font}[")), None)
        if start is None:
            sys.exit(f"font not found: {font}")
        end = start
        while not source[end].rstrip().endswith('";'):
            end += 1
        out.extend(source[start:end + 1])
        out.append("")
        size = int(re.search(r"\[(\d+)\]", source[start]).group(1))
        total += size
        print(f"  {font}: {size} bytes")
    with open(os.path.join(DEST, "miblo_fonts.c"), "w", encoding="latin-1") as f:
        f.write("\n".join(out) + "\n")
    print(f"total font size: {total} bytes")


if __name__ == "__main__":
    main()
